# Generated by Django 3.2 on 2021-12-23 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_m_services_m_subservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.CharField(max_length=1000)),
                ('Address', models.TextField()),
                ('Comments', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ServiceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.m_subservices')),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
