# Generated by Django 3.2 on 2022-01-15 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='Offers/')),
                ('OfferCode', models.CharField(max_length=30, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Archived', 'Archived'), ('Cancelled', 'Cancelled')], default='Active', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
