# Generated by Django 3.2 on 2022-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_requestassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestassign',
            name='bookingStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Archived', 'Archived'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
    ]
