# Generated by Django 3.2 on 2022-05-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_requestassign_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_subservices',
            name='MainService',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mservice', to='api.m_services'),
            preserve_default=False,
        ),
    ]
