# Generated by Django 3.2 on 2022-05-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_m_subservices_mainservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_requests',
            name='ServiceID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subservice', to='api.m_subservices'),
            preserve_default=False,
        ),
    ]
